// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Ufd8ZKx6dJHaITE5fEKWKGZvgBc30Dk',
    appId: '1:902997511264:web:f247741fd3855e110cc705',
    messagingSenderId: '902997511264',
    projectId: 'up-store-1634a',
    authDomain: 'up-store-1634a.firebaseapp.com',
    storageBucket: 'up-store-1634a.firebasestorage.app',
    measurementId: 'G-J293ZPRP3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU54dtc5u68tiFhcEw0Cm_Wkfi-yiCGZ0',
    appId: '1:902997511264:android:65d5a517021fc54f0cc705',
    messagingSenderId: '902997511264',
    projectId: 'up-store-1634a',
    storageBucket: 'up-store-1634a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbHPs3FhVSrRuVEhykUx8R-WWTDtS0erU',
    appId: '1:902997511264:ios:284e33acb2b85e040cc705',
    messagingSenderId: '902997511264',
    projectId: 'up-store-1634a',
    storageBucket: 'up-store-1634a.firebasestorage.app',
    iosBundleId: 'com.example.upStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbHPs3FhVSrRuVEhykUx8R-WWTDtS0erU',
    appId: '1:902997511264:ios:284e33acb2b85e040cc705',
    messagingSenderId: '902997511264',
    projectId: 'up-store-1634a',
    storageBucket: 'up-store-1634a.firebasestorage.app',
    iosBundleId: 'com.example.upStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Ufd8ZKx6dJHaITE5fEKWKGZvgBc30Dk',
    appId: '1:902997511264:web:b80b7b426742d9fa0cc705',
    messagingSenderId: '902997511264',
    projectId: 'up-store-1634a',
    authDomain: 'up-store-1634a.firebaseapp.com',
    storageBucket: 'up-store-1634a.firebasestorage.app',
    measurementId: 'G-D517GX5D4M',
  );
}
